### ISSUE TITLE
[not good at github] request Magisk

### ISSUE THREAD

**Issue by micheleberrettis1** [Moyster/nougat_device_meizu_m2note#12]
Could you add Magisk systemless root to next build?

**Comment by Moyster** [comment]
Hey there, 

I'm trying to keep the rom as close as LineageOS, this means I don't ship "su / root" enabled roms, nor do I had 3rd party apps, nor 3rd party mods (Magisk / SuperSu / Xposed / etc...)
The reason is simple, not everyone uses these, and enabling root/magisk, etc.. can be a security problem as it weakens the system. Also these mods are "most of the time" a simple .zip you can flash during rom flash / update ;)

**Comment by micheleberrettis1** [comment]
Oh OK, thanks anyway for your amazing work :)
