### ISSUE TITLE
[Build 15 (RC 5 "Summertime")] After Setup is done and then phone Restart, Setup Wizard starts up

### ISSUE THREAD

**Issue by dariusworks** [Moyster/nougat_device_meizu_m2note#50]
OpenGAPPS + "https://forum.xda-developers.com/attachment.php?attachmentid=4100012&d=1491250714" camera fix

After setup, and some usage when you restart your phone it will want to do setup again. 
This wasn't happening in "lineage-14.1-20170225-UNOFFICIAL-m2note" build

**Comment by Moyster** [comment]
I don't think this has to do with the rom, try a backup + a clean wipe.  
Setup shouldn't start since the phone remember its' first boot (and if it needs to start the setup wizard).
This is not happening to me, feel free to comment if you have more infos.

ps: you don't need the camera fix, try and download a more recent Gapps package.
